name: frontend_seminario
description: "Frontend Sistema de gestion de consorcios Facundo Flores."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  form_field_validator: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  go_router: ^14.2.0
  jwt_decoder: ^2.0.1
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.13.1
  universal_html: ^2.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true
