name: frontend_seminario
description: "Frontend Sistema de gestion de consorcios Facundo Flores."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  form_field_validator: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

assets:
  - .env.development

flutter:
  uses-material-design: true
